


POST  http://localhost:3000/admin/create
###

GET http://localhost:3000/show/table

###

DELETE  http://localhost:3000/sample/send/

###

POST http://localhost:3000/user/register
Content-Type: application/json

{
  "email": "kane",
  "password": "veeraPspk",
  "phone": "9339393939",
  "fullName": "veerabau"
}

###



POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email":"qwer",
  "password":"veeraPspk"
}
###

POST http://localhost:3000/user/request/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InF3ZXIiLCJpYXQiOjE2ODI1ODk2NTJ9.tQOPv4XUgTuKZBd2lCTIQMRS2tNH3T430t_LAdRpvbo


{
    "woolen":"10"
}

###
PUT http://localhost:3000/user/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImthbmUiLCJpYXQiOjE2ODIyNDQ2NDB9.Xr4xa8sOHGps15BP75ATdvn33PQsRbfpyzoyKHhq1k4



{
  "newEmail":"rose",
  "newPassword":"9182007102",
  "newFullName":"jhon",
   "newPhone":"87878787878"
}

###
GET http://localhost:3000/user/data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InF3ZXIiLCJpYXQiOjE2ODI1ODk2NTJ9.tQOPv4XUgTuKZBd2lCTIQMRS2tNH3T430t_LAdRpvbo






###

POST http://localhost:3000/request
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBzcGsiLCJpYXQiOjE2ODIyMzIzNzJ9.is63Pw83rRAKAb_t_h7347Uo-LEPBTOOZelNk48Kiak


