


###

GET http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MTgxNzE0fQ.0pKPbVnX3_bCuvtFacF3c3zYC1wkACj7ZeZst8nSA0w

###
// api 4

GET http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MTgxNzE0fQ.0pKPbVnX3_bCuvtFacF3c3zYC1wkACj7ZeZst8nSA0w

###
//api 5

GET http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MTgxNzE0fQ.0pKPbVnX3_bCuvtFacF3c3zYC1wkACj7ZeZst8nSA0w

###


// api 7

GET http://localhost:3000/tweets/1/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MTgxNzE0fQ.0pKPbVnX3_bCuvtFacF3c3zYC1wkACj7ZeZst8nSA0w

###

//api 8

GET http://localhost:3000/tweets/1/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MTgxNzE0fQ.0pKPbVnX3_bCuvtFacF3c3zYC1wkACj7ZeZst8nSA0w


###
// api 9

GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MTgxNzE0fQ.0pKPbVnX3_bCuvtFacF3c3zYC1wkACj7ZeZst8nSA0w


###
POST http://localhost:3000/user/tweets/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY5MTgxNzE0fQ.0pKPbVnX3_bCuvtFacF3c3zYC1wkACj7ZeZst8nSA0w

{
   "tweet": "The Mornings..."
}

###
GET  http://localhost:3000/sample/add

###

PUT http://localhost:3000/sample/show

###

POST http://localhost:3000/sample/send/

###

POST http://localhost:3000/user/register
Content-Type: application/json

{
  "email": "kane",
  "password": "veeraPspk",
  "phone": "9339393939",
  "fullName": "veerabau"
}

###



POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email":"kane",
  "password":"veeraPspk"
}

###
PUT http://localhost:3000/user/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBzcGsiLCJpYXQiOjE2ODIyMzIzNzJ9.is63Pw83rRAKAb_t_h7347Uo-LEPBTOOZelNk48Kiak


{
  "newEmail":"rose",
  "newPassword":"9182007102",
  "newFullName":"jhon",
   "newPhone":"87878787878"
}

###
GET http://localhost:3000/user/data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvc2UiLCJpYXQiOjE2ODIyMzQ0MzR9.2jJUVPtUWffvVhHuFjf-DxiqkN3JhlB9BQ7khBJ1Ckk





###

POST http://localhost:3000/request
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBzcGsiLCJpYXQiOjE2ODIyMzIzNzJ9.is63Pw83rRAKAb_t_h7347Uo-LEPBTOOZelNk48Kiak


